#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_add_task:
  path: /api/todo
  controller: App\Infrastructure\EntryPoint\Api\TodoListController::addTask
  methods: ['POST']

api_get_task_list:
  path: /api/todo
  controller: App\Infrastructure\EntryPoint\Api\TodoListController::getTasksList
  methods: ['GET']
