api_add_task:
  path: /api/todo
  controller: App\Infrastructure\EntryPoint\Api\Controller\TodoListController::addTask
  methods: ['POST']

api_mark_task_completed:
  path: /api/todo/{taskid}
  controller: App\Infrastructure\EntryPoint\Api\Controller\TodoListController::markTaskCompleted
  methods: ['PATCH']

api_get_tasks_list:
  path: /api/todo
  controller: App\Infrastructure\EntryPoint\Api\Controller\TodoListController::getTasksList
  methods: ['GET']
